on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allows the action to create a release.
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y librsvg2-bin
          pwsh -File ./tools/build.ps1 -a pink
          pwsh -File ./tools/build.ps1 -a purple
      - uses: actions/upload-artifact@v3
        with:
          name: dracula-artifact
          path: ./build/*.*
        if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
      - if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          files=$(find ./build -maxdepth 1 -type f)
          pwsh -File ./tools/changelog.ps1 > ./release_notes.txt
          gh release create ${{ github.ref_name }} $files \
            --title ${{ github.ref_name }} \
            --notes-file ./release_notes.txt \
            --generate-notes \
            --draft=false \
            --prerelease=false \
            --verify-tag
